from typing import Any

from simple_crew.tasks.common import TOOL_SCHEMA, compact


def build_task(objective: str, context: dict[str, Any]) -> str:
    return f"""Generate one small local tool for this authorized Red Team objective: {objective}
The tool must be complete, reviewable, bounded to the supplied target and target_port, and low impact. Its command array must be immediately runnable by the executor: include the interpreter, generated filename, target, port, and every other required argument. Do not require interactive input or omit mandatory arguments. Prefer Python standard library or simple argument-list subprocess calls. Never use shell=True, destructive changes, credential attacks, persistence, evasion, lateral movement, malware, or denial of service. Do not embed secrets. The code must fail clearly when inputs or dependencies are missing.
Keep Python helpers compact (at most 60 non-blank lines, or at most 100 when one explicitly requested authorization matrix requires multiple HTTP requests). Do not include a module docstring, usage examples, repeated comments, or explanatory prose inside the code. The JSON and the complete source code must fit in one response; never return partial source.
An evidence collector must print its bounded results. A validator must also exit nonzero unless every confirmation condition in the objective is satisfied; transport success alone is not validation success. For a JSON HTTP API, send an explicit JSON Accept header supported by the supplied evidence (use `application/vnd.api+json` for a Joomla JSON:API endpoint), parse nested response objects as required by the objective, and treat unexpected status codes or response shapes as failure.
Every command argument must be a literal value. Never emit shell syntax such as command substitution, dollar expansion, backticks, pipes, redirects, semicolons, or boolean shell operators. If a unique marker is needed, generate it inside Python with uuid.uuid4 or secrets.token_hex, print it as evidence, and use the same value for verification and cleanup.
When pre-exploitation context is supplied, derive the collector only from its target, endpoints,
identity data, test names, variations, evidence requirements, and safety rules. Do not assume
product-specific paths, headers, roles, identifiers, payload fields, expected responses, or
verdicts. Cover the applicable context-defined matrix in one bounded run. Preserve denied responses
as evidence, verify state-changing tests, and restore temporary changes.
For Nmap collection, do not generate Python that imports subprocess. Generate a small shell tool containing one literal bounded nmap invocation, with target and port accepted as positional arguments and validated before use. The executable command must invoke bash with that generated filename, target, and port. Do not use pipes, redirects, command substitution, additional hosts, UDP scanning, OS detection, NSE scripts, or broad port ranges unless the objective explicitly authorizes them.
For a named CVE, attribute validation to that CVE only when the exact mechanism is supported by an exact database record or observed evidence. When the exact record is absent, you may generate a generic evidence-driven capability validator without CVE attribution. For an authorized HTTP lab, this may create one unpredictable harmless .txt marker, retrieve it and compare the exact content, then remove it in a finally block. It must not upload JSP, executable content, commands, credentials, or overwrite an existing resource. Cleanup is mandatory: do not ignore DELETE errors, do not print that deletion succeeded merely because a request was sent, and verify cleanup with a final GET that must return 404 or 410. Exit nonzero if content verification or cleanup verification fails. Treat successful creation plus exact retrieval as confirmation of file-write capability, not automatic confirmation of any CVE. Never substitute another CVE, AJP, proxy headers, or an unrelated protocol.
For command-injection validation, a random marker placed by itself in a header or parameter is not an exploit test. When exact evidence supplies a trigger syntax and injection location, the generated request must use that trigger to run only a harmless marker-output command. Compare against a patched endpoint or equivalent negative control when supplied. Success requires the unpredictable marker in the vulnerable response and its absence from the negative control; otherwise exit nonzero and report inconclusive. Keep trigger construction inside Python so the executor command array contains no shell syntax.
When validating command injection through a CGI program, ensure injected output remains a valid CGI response: emit a valid Content-Type header and the required blank line before the marker, unless supplied evidence shows the CGI script has already emitted them. A server error is not confirmation.
Return only one JSON object matching: {TOOL_SCHEMA}
Context: {compact(context, 7000)}"""
